Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream10"
  # config.vm.box_check_update = false

  config.vm.network "public_network", dev: "wlp0s20f3"

  config.vm.hostname = "ecomwebserver"

  # Example for VirtualBox:
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.cpus = 2
      vb.name = "webserver-ecom-centos"     
  end
 
  config.vm.provision "shell", inline: <<-SHELL
   
    sudo yum update -y
    sudo yum install httpd php php-mysqlnd -y
    
    sudo systemctl start httpd
    sudo systemctl enable httpd

    # allow httpd service to connect to databases like mysql
    sudo setsebool -P httpd_can_network_connect_db 1 

  SHELL
end
