Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream10"
  # config.vm.box_check_update = false

  config.vm.network "public_network", dev: "wlp0s20f3"

  config.vm.hostname = "ecomwebserver"
  
  # Variables
  VM_USERNAME = ENV["VM_USERNAME"] | "default"
  VM_USER_PASSWORD = ENV["VM_USER_PASSWORD"] | "default"

  # Example for VirtualBox:
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.cpus = 2
      vb.name = "webserver-ecom-centos"     
  end
 
  config.vm.provision "shell", inline: <<-SHELL
   
    sudo yum update -y
    sudo yum install httpd php php-mysqlnd -y
    
    sudo systemctl start httpd
    sudo systemctl enable httpd

    # allow httpd service to connect to databases like mysql
    sudo setsebool -P httpd_can_network_connect_db 1 
   
    # config your host user on the vm 
    sudo useradd -m #{VM_USERNAME}
    echo #{VM_USER_PASSWORD} | sudo passwd -s #{VM_USERNAME}
    sudo usermod -aG wheel #{VM_USERNAME}

    sudo yum install git -y
    sudo git clone https://github.com/leonardo-rothier/learning-app-ecommerce /var/www/html/
  SHELL
end
