Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream10"
  # config.vm.box_check_update = false

  config.vm.network "public_network", dev: "wlp0s20f3"

  config.vm.hostname = "ecomdb"
  
  # Variables
  VM_USERNAME = ENV["VM_USERNAME"] || "default"
  VM_USER_PASSWORD = ENV["VM_USER_PASSWORD"] || "default"

  # Example for VirtualBox:
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
      vb.memory = "1024"
      vb.cpus = 3
      vb.name = "db-ecom-centos"     
  end
  
  # bring db script file to db host 
  config.vm.provision "file", source: "ecom-db-script.sql", destination: "/tmp/ecom-db-script.sql"

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update -y
    curl https://repo.mysql.com//mysql84-community-release-el9-1.noarch.rpm -O
    sudo rpm -Uvh mysql84-community-release-el9-1.noarch.rpm 
    
    sudo yum update

    sudo yum install mysql-server -y
    sudo systemctl start mysqld.service 
    sudo systemctl enable mysqld.service

    # config my host user to access it
    sudo useradd -m #{VM_USERNAME}
    echo #{VM_USER_PASSWORD} | sudo passwd -s #{VM_USERNAME}
    sudo usermod -aG wheel #{VM_USERNAME}
    
    sudo mv /tmp/ecom-db-script.sql /opt/ecom-db-script.sql
  SHELL
end
